name: miniset
channels:
  - conda-forge
  - usgs-astrogeology
dependencies:
  - cmake>=3.15
  - make
  - cxx-compiler
  - csmapi>=1.0
  - usgscsm>=2.0
  - gdal>=3.8,<4
  - libgdal-arrow-parquet>=3.8,<4  # OGR Parquet driver for control networks
  - proj>=9,<10
  - eigen>=3.3
  - suitesparse
  - gtest>=1.10
  - gmock>=1.10
  - llvm-openmp 
  - pkg-config
  - ninja  
  - doxygen
