/**
 * Miniset WASM Module
 * Integrates GDAL C functions with Miniset C++ functionality
 */

import MinisetFactory from './miniset_core.js'; // Generated by Emscripten
import { initGDALFunctions, extractEllipsoidFromDEM, GDALFunctions } from './gdal_functions.js';

let moduleInstance = null;

/**
 * Initialize Miniset WASM module
 * @returns {Promise<Object>} Miniset module with GDAL integration
 */
export async function initMiniset() {
    if (moduleInstance) {
        return moduleInstance;
    }

    console.log('Initializing Miniset WASM module...');

    // Load the Emscripten-generated module
    const Module = await MinisetFactory();

    console.log('Emscripten module loaded');

    // Initialize GDAL C function wrappers
    initGDALFunctions(Module);

    // Create enhanced module with GDAL integration
    moduleInstance = {
        Module,
        GDALFunctions,

        /**
         * Create a DEM with automatic spatial reference extraction
         * @param {string} filepath Path to DEM file in WASM filesystem
         * @param {number} demType DEM type (HEIGHT or RADIUS)
         * @returns {Object} DEM instance with correct ellipsoid
         */
        createDEM(filepath, demType = Module.DEMType.HEIGHT) {
            console.log(`Creating DEM from ${filepath}...`);

            // Extract ellipsoid using JavaScript GDAL functions (works!)
            const ellipsoid = extractEllipsoidFromDEM(filepath);

            // Create DEM instance (C++ constructor, defaults to WGS84)
            const dem = new Module.GdalDEM(filepath, demType);

            // If we extracted a valid ellipsoid, set it
            if (ellipsoid.isValid) {
                console.log(`Setting ellipsoid: a=${ellipsoid.semiMajor}, b=${ellipsoid.semiMinor}`);

                // Create WKT from ellipsoid to pass to setProj
                // For now, create a simple GEOGCS WKT
                const wkt = `GEOGCS["Custom",DATUM["Custom",SPHEROID["Custom",${ellipsoid.semiMajor},${
                    ellipsoid.semiMajor / (ellipsoid.semiMajor - ellipsoid.semiMinor)
                }]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433]]`;

                try {
                    dem.setProj(wkt);
                } catch (e) {
                    console.warn('setProj failed, trying direct WKT extraction...');
                    // Extract full WKT and use that
                    const GA_ReadOnly = 0;
                    const dataset = GDALFunctions.GDALOpen(filepath, GA_ReadOnly);
                    if (dataset) {
                        const fullWkt = GDALFunctions.GDALGetProjectionRef(dataset);
                        GDALFunctions.GDALClose(dataset);
                        if (fullWkt && fullWkt.length > 0) {
                            dem.setProj(fullWkt);
                        }
                    }
                }
            }

            return dem;
        },

        /**
         * Extract spatial reference WKT from a DEM file
         * @param {string} filepath Path to DEM file
         * @returns {string|null} WKT string or null
         */
        extractSpatialReference(filepath) {
            const GA_ReadOnly = 0;
            const dataset = GDALFunctions.GDALOpen(filepath, GA_ReadOnly);
            if (!dataset) {
                return null;
            }

            try {
                return GDALFunctions.GDALGetProjectionRef(dataset);
            } finally {
                GDALFunctions.GDALClose(dataset);
            }
        },

        // Expose underlying modules
        FS: Module.FS,
        DEMType: Module.DEMType,
        GdalDEM: Module.GdalDEM,
        EllipsoidDEM: Module.EllipsoidDEM,
    };

    console.log('Miniset WASM module ready');

    return moduleInstance;
}

export default initMiniset;
